endpoints:
    nhl_base: https://statsapi.web.nhl.com
    nhl_endpoint: https://statsapi.web.nhl.com/api/v1
    nhl_rpt_base: https://api.nhle.com/stats/rest/en/team
    nhl_score_rpt_base: http://www.nhl.com/scores/htmlreports
    twitter_url: https://twitter.com/NJDevilsGameBot/status/
    twitter_handle: NJDevilsGameBot
    debug_twitter_handle: DevilsBotDebug
    df_starting_goalies: https://www.dailyfaceoff.com/starting-goalies/
    # df_starting_goalies: https://www.dailyfaceoff.com/starting-goalies/09-17-2019/
    df_line_combos: https://www.dailyfaceoff.com/teams/TEAMNAME/line-combinations/
    hockeyref_base: https://www.hockey-reference.com/players
    scouting_refs: http://scoutingtherefs.com/wp-json/wp/v2/posts
    nst: https://www.naturalstattrick.com
    hockey_stat_cards: https://api.hockeystatcards.com/webapi